### PR TITLE
Enable Screen Cast feature (Miracast)

### PR DESCRIPTION
**Pull request by Vioner**
Without this, Redmi 3 won't see any screens to stream to. 
Tested on Redmi 3 Pro, works just fine, but settings app crashes in Cast menu.
Not a problem though. 

Tested with screen cast debugging developer option enabled and with Substratum theme applied.

I think it's safe to push.

### CODE REVIEW

**Comment by kmahyyg** [comment]
@Vioner cuz I don't have miracast device , I think that substratum theme caused crash.
Plz disable OMS theme and then see if it still crashed.

**Comment by Vioner** [comment]
I was planning to do that tomorrow @kmahyyg
I'll let you know.

**Comment by kmahyyg** [comment]
If it doesn't work , plz attach crash logcat here.Thanks.

**Comment by Vioner** [comment]
@kmahyyg 
I disabled the Substratum theme and there are no crashes. Miracast fully functional, video and audio work nicely.

**Comment by kmahyyg** [comment]
got it.it will be merged later.

**Pull request merged**
